CREATE TABLE AERODROM (
    ID_AERODROMA INT PRIMARY KEY NOT NULL,
    KOD_AERODROMA VARCHAR(50) NOT NULL,
    NAZIV_AERODROMA VARCHAR(100) NOT NULL,
    LOKACIJA VARCHAR(100) NOT NULL
);

CREATE TABLE KOMPANIJA (
    ID_KOMPANIJE INT PRIMARY KEY NOT NULL,
    NAZIV_KOMPANIJE VARCHAR(100) NOT NULL,
    ADRESA VARCHAR(100) NOT NULL,
    KONTAKT_OSOBA VARCHAR(50) NOT NULL,
    TELEFON VARCHAR(20) NOT NULL,
    PROCENAT_ROYALTY_BODOVA DECIMAL(5, 2) NOT NULL
);

CREATE TABLE AVION (
    ID_AVIONA INT PRIMARY KEY NOT NULL,
    ID_KOMPANIJE INT NOT NULL,
    NAZIV_AVIONA VARCHAR(100) NOT NULL,
    TIP VARCHAR(50) NOT NULL,
    PROIZVODJAC VARCHAR(50) NOT NULL,
    KAPACITET INT NOT NULL,
    FOREIGN KEY (ID_KOMPANIJE) REFERENCES KOMPANIJA(ID_KOMPANIJE)
);

CREATE TABLE PILOT (
    ID_PILOTA INT PRIMARY KEY NOT NULL,
    ID_KOMPANIJE INT NOT NULL,
    IME VARCHAR(50) NOT NULL,
    PREZIME VARCHAR(50) NOT NULL,
    BROJ_LICENCE VARCHAR(50) NOT NULL,
    FOREIGN KEY (ID_KOMPANIJE) REFERENCES KOMPANIJA(ID_KOMPANIJE)
);

CREATE TABLE POSADA (
    ID_OSOBLJA_POSADE INT PRIMARY KEY NOT NULL,
    ID_KOMPANIJE INT NOT NULL,
    IME VARCHAR(50) NOT NULL,
    PREZIME VARCHAR(50) NOT NULL,
    BR_LICENCE VARCHAR(50) NOT NULL,
    POZICIJA VARCHAR(50) NOT NULL,
    FOREIGN KEY (ID_KOMPANIJE) REFERENCES KOMPANIJA(ID_KOMPANIJE)
);

CREATE TABLE SJEDISTE (
    ID_SJEDISTA INT PRIMARY KEY NOT NULL,
    ID_AVIONA INT NOT NULL,
    TIP_SJEDISTA VARCHAR(50) NOT NULL,
    BROJ_SJEDISTA INT NOT NULL,
    DOSTUPNOST VARCHAR(50) NOT NULL,
    FOREIGN KEY (ID_AVIONA) REFERENCES AVION(ID_AVIONA)
);

CREATE TABLE KORISNIK (
    ID_KORISNIKA INT PRIMARY KEY NOT NULL,
    KORISNICKO_IME VARCHAR(50) NOT NULL,
    LOZINKA VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    IME VARCHAR(50) NOT NULL,
    PREZIME VARCHAR(50) NOT NULL,
    TELEFON VARCHAR(20) NOT NULL,
    BROJ_PASOSA VARCHAR(20) NOT NULL,
    BROJ_BODOVA INT NOT NULL
);

CREATE TABLE REZERVACIJA (
    ID_REZERVACIJE INT PRIMARY KEY NOT NULL,
    ID_KORISNIKA INT NOT NULL,
    ID_SJEDISTA INT NOT NULL,
    VRIJEME_REZERVACIJE DATETIME NOT NULL,
    DATUM_REZERVACIJE DATE NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    CIJENA_PRTLJAGA DECIMAL(10, 2) NOT NULL, 
    FOREIGN KEY (ID_KORISNIKA) REFERENCES KORISNIK(ID_KORISNIKA),
    FOREIGN KEY (ID_SJEDISTA) REFERENCES SJEDISTE(ID_SJEDISTA)
);

CREATE TABLE KUPOVINA (
    ID_KUPOVINE INT PRIMARY KEY NOT NULL,
    ID_REZERVACIJE INT,
    NAZIV_OBJEKTA VARCHAR(100) NOT NULL,
    IZNOS DECIMAL(10, 2) NOT NULL,
    DATUM_KUPOVINE DATE NOT NULL,
    ZARADJENI_BONUS_BODOVI INT NOT NULL,
    POPUST DECIMAL(5, 2) NOT NULL,
    NACIN_PLACANJA_CREDIT_CARD VARCHAR(50),
    PAY_PAL VARCHAR(50),
    CIJENA_DODATNIH_TAKSI DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (ID_REZERVACIJE) REFERENCES REZERVACIJA(ID_REZERVACIJE)
);

CREATE TABLE LET (
    ID_LETA INT PRIMARY KEY NOT NULL,
    ID_AVIONA INT NOT NULL,
    ID_AERODROMA_POLASKA INT NOT NULL,
    ID_AERODROMA_DOLASKA INT NOT NULL,
    DATUM_POLASKA DATE NOT NULL,
    VRIJEME_POLASKA TIME NOT NULL,
    DATUM_DOLASKA DATE NOT NULL,
    VRIJEME_DOLASKA TIME NOT NULL,
    TRAJANJE DECIMAL(5, 2) NOT NULL,
    CENA_EKONOMSKA_KLASA DECIMAL(10, 2) NOT NULL,
    CENA_PRVA_KLASA DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (ID_AVIONA) REFERENCES AVION(ID_AVIONA),
    FOREIGN KEY (ID_AERODROMA_POLASKA) REFERENCES AERODROM(ID_AERODROMA),
    FOREIGN KEY (ID_AERODROMA_DOLASKA) REFERENCES AERODROM(ID_AERODROMA)
);

CREATE TABLE KARTA (
    ID_KARTE INT PRIMARY KEY NOT NULL,
    ID_KUPOVINE INT NOT NULL,
    IME_PUTNIKA VARCHAR(50) NOT NULL,
    PREZIME_PUTNIKA VARCHAR(50) NOT NULL,
    BROJ_SJEDISTA INT NOT NULL,
    CIJENA DECIMAL(10, 2) NOT NULL,
    ID_LETA INT NOT NULL,
    FOREIGN KEY (ID_KUPOVINE) REFERENCES KUPOVINA(ID_KUPOVINE),
    FOREIGN KEY (ID_LETA) REFERENCES LET(ID_LETA)
);

CREATE TABLE PRTLJAG (
    ID_PRTLJAGA INT PRIMARY KEY NOT NULL,
    ID_KARTE INT NOT NULL,
    MASA DECIMAL(5, 2) NOT NULL,
    VELICINA VARCHAR(50) NOT NULL,
    OPIS VARCHAR(100),
    FOREIGN KEY (ID_KARTE) REFERENCES KARTA(ID_KARTE)
);

