-- SELECT
SELECT * FROM KORISNIK;

-- JOIN
SELECT r.ID_REZERVACIJE, k.IME, k.PREZIME, l.DATUM_POLASKA, a_pol.NAZIV_AERODROMA AS POLAZAK, a_dol.NAZIV_AERODROMA AS DOLAZAK
FROM REZERVACIJA r
JOIN KORISNIK k ON r.ID_KORISNIKA = k.ID_KORISNIKA
JOIN KARTA ka ON r.ID_REZERVACIJE = ka.ID_KUPOVINE
JOIN LET l ON ka.ID_LETA = l.ID_LETA
JOIN AERODROM a_pol ON l.ID_AERODROMA_POLASKA = a_pol.ID_AERODROMA
JOIN AERODROM a_dol ON l.ID_AERODROMA_DOLASKA = a_dol.ID_AERODROMA;

-- SUBQUERY
SELECT * FROM KORISNIK
WHERE BROJ_BODOVA = (SELECT MAX(BROJ_BODOVA) FROM KORISNIK);

--AGGREG.
SELECT SUM(IZNOS) AS UKUPAN_IZNOS FROM KUPOVINA;

-- VIEW
CREATE VIEW PREGLED_REZERVACIJA AS
SELECT r.ID_REZERVACIJE, k.IME, k.PREZIME, r.VRIJEME_REZERVACIJE, r.DATUM_REZERVACIJE
FROM REZERVACIJA r
JOIN KORISNIK k ON r.ID_KORISNIKA = k.ID_KORISNIKA;

SELECT * FROM PREGLED_REZERVACIJA;

--STORED PROCEDURE
CREATE PROCEDURE GET_KORISNICI_BY_PREZIME
    @p_slovo CHAR(1)
AS
BEGIN
    SELECT *
    FROM KORISNIK
    WHERE PREZIME LIKE @p_slovo + '%';
END;

EXEC GET_KORISNICI_BY_PREZIME @p_slovo = 'A';


